location            = "eastus"
resource_group_name = "rg-windows-vm"
vm_name             = "windows-vm"
vm_size             = "Standard_B1ms"
admin_username      = "azureadmin"
admin_password      = "ReplaceWithAStrongPassword12!"
rdp_source_cidr     = "203.0.113.10/32"
